version: '2'

services:
  nginx:
    image: bitnami/nginx:1.10.2-r4
    volumes:
      - ./config/nginx:/bitnami/nginx/conf/vhosts
    depends_on:
      - rails
      - react
    environment:
      - VIRTUAL_HOST=billtalk.docker
      - VIRTUAL_PORT=8080
    ports:
      - 8080:8080
  rails:
    build: .
    command: rails s --binding=0.0.0.0
    entrypoint: ./scripts/entrypoint.sh
    links:
      - database
      - react
    volumes:
      - ./:/app
    depends_on:
      - database
      - react
  react:
    build: ./client
    command: npm start
    entrypoint: ./scripts/entrypoint.sh
    volumes:
      - ./client:/app
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
  database:
    image: convox/postgres
    labels:
      - convox.health.timeout=60
    ports:
      - 5432
    volumes:
      - /var/lib/postgresql/data
