default: &default
  adapter: postgresql
  username: postgres
  encoding: utf8
  host: 127.0.0.1

development:
  <<: *default
  database: billtalk_development

test:
  <<: *default
  database: billtalk_test

production:
  <<: *default
  database: billtalk
